INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Familia');
INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Amigo');
INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Namorado');
INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Namorada');
INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Trabalho');
INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Escola');

INSERT INTO TBL_CONTACT (ADDRESS, CATEGORY_ID, CELL, DATEBIRTH, EMAIL, FAVORITE, NAME, LASTNAME, NOTE, PHONE) VALUES ('rua das palmeiras', 2, '(11) 97474-6553', '2000-10-19', 'teste@mail.com', false, 'Fulano', 'Silva', 'Gente boa','24421');
INSERT INTO TBL_CONTACT (ADDRESS, CATEGORY_ID, CELL, DATEBIRTH, EMAIL, FAVORITE, NAME, LASTNAME, NOTE, PHONE) VALUES ('rua reversão', 1, '(11) 97598-3253', '1985-07-12', 'teste1@mail.com', false, 'Gimenes', 'Oliveira', 'O melhor','1234142');
INSERT INTO TBL_CONTACT (ADDRESS, CATEGORY_ID, CELL, DATEBIRTH, EMAIL, FAVORITE, NAME, LASTNAME, NOTE, PHONE) VALUES ('rua filomena', 4, '(11) 93984-76543', '2005-08-20', 'teste2@mail.com', true, 'Filó', 'Nogueira', 'Minha vida','124124');